### create
POST localhost:8080/api/kombuchas
Content-Type: application/json

{
  "name": "Kombucha 1",
  "flavor": "Ginger"
}

### find all
GET localhost:8080/api/kombuchas


### delete by id
DELETE localhost:8080/api/kombuchas/64f7011c550096149110838e